name: Prepare Deployment

on:
  push:
    branches:
      - main  # Assuming you're deploying from the 'main' branch, change if necessary

jobs:
  prepare:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Replace API Key
      run: |
        sed -i.bak 's/REPLACE_WITH_API_KEY/${{ secrets.API_KEY_NINJAS }}/g' ./src/ts/fetchQuotes.ts && rm ./src/ts/fetchQuotes.ts.bak
    - name: Commit changes
      run: |
        git config --local user.email "marjoriekohn@icloud.com"
        git config --local user.name "marjoriekohn"
        git commit -am "Replace API key placeholder" || echo "No changes to commit"
        git push
